language: python

sudo: required
dist: trusty

virtualenv:
  system_site_packages: true

matrix:
  include:
    - python:
        - "3.4"
        - "pypy3.5"
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8-dev"
      addons:
        apt:
          packages:
            - python3-gi
            - gir1.2-gtk-3.0
            - gir1.2-notify-0.7
            - gir1.2-secret-1
            - gir1.2-wnck-3.0
            - gettext
            - intltool
            - desktop-file-utils
      install:
        - pip install six

script:
  - python setup.py build test
  - desktop-file-validate viagee.desktop
  - desktop-file-validate viagee-startup.desktop
